### ISSUE TITLE
gzip needs to depend on a gzip accept header!

### ISSUE THREAD

**Issue by frank-dspeed** [stealjs/steal-push#3]
> Not all browser support gzip you need to check the req accept header for that.
https://github.com/stealjs/steal-push/blob/master/lib/index.js#L70,L76

> sorry that the link don't marks the indipendent lines we are working on that as soon as github mergs isaccs pulls this will show up right :) https://github.com/isaacs/github/issues/453 https://github.com/isaacs/github/issues/9

**Comment by matthewp** [comment]
Ah, good point, thanks.

**Comment by frank-dspeed** [comment]
@matthewp no need to thanks for that you already payed back as i don't knowed about the .push prototype :) i setted push headers directly on the res :) but i have a little extra tip for you so that i added value you should only use the req object it holds a response prototype normaly

this way your more compatible to more nodejs server side frameworks:
for example: http://dietjs.com/ wich only uses one property that we call signal
